# This code was automatically generated by CWrap.

cdef extern from "test.h":

    ctypedef long long int LLong

    cdef struct Foo:
        int a
        LLong b

    cdef struct _Bar:
        double b

    ctypedef _Bar Bar

    cdef enum Baz:
        ONE
        TWO
        THREE
        FOUR
        FIVE

    ctypedef Baz Spam

    ctypedef Foo Eggs

    cdef struct __fake_AUnion__sNested:
        char *data

    ctypedef __fake_AUnion__sNested __fake_AUnion__sNested_t

    cdef union AUnion:
        int a
        double b
        long double c
        __fake_AUnion__sNested_t nested_data

    cdef union __fake__Astruct__uNested:
        float *data

    ctypedef __fake__Astruct__uNested __fake__Astruct__uNested_t

    cdef struct _Astruct:
        Eggs *eggsPtr
        __fake__Astruct__uNested_t nested_data

    ctypedef _Astruct Astruct

    int *foo_bar(double t, Bar *barptr)

    double *((*crazy_fn(int *, char *, Baz))[10])

    ctypedef char *((*(*crazy_fn_ptr_)(void *))[42])

